- op: replace
  path: /spec/template/spec/domain/memory/guest
  value: 4096M
- op: replace
  path: /spec/running
  value: true
- op: add
  path: /spec/template/spec/accessCredentials
  value:
    - sshPublicKey:
        propagationMethod:
          noCloud: {}
        source:
          secret:
            secretName: ssh-bastion-access
