apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: centos9-disk
  namespace: gitops-virt
spec:
  source:
    http:
      url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
