apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: base-vm 
  name: base-vm
  namespace: beehive-virtual-machines
spec:    
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/domain: base-vm    
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          memory:
            guest: 2048M
          devices:
            disks:
            - disk:
                bus: virtio
              name: vm-rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        volumes:
        - persistentVolumeClaim:
              claimName: base-vm-disk
          name: vm-rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: 'redhat1234' 
              chpasswd: { expire: False }
              packages:
                - nginx
                - firewalld
                - openssh-server
              runcmd:
                - echo "CLOUD-INIT TEST OK" > /root/cloud-init-test.txt
                - systemctl enable sshd
                - systemctl start sshd
                - systemctl enable firewalld
                - systemctl start firewalld
                - systemctl enable nginx
                - systemctl start nginx
                - firewall-cmd --permanent --add-service=ssh
                - firewall-cmd --permanent --add-service=http
                - firewall-cmd --permanent --add-service=https
                - firewall-cmd --reload
                - [ /bin/bash, -c, 'echo "<h1>GitOps com ArgoCD + Cloud-Init!</h1><h2>Servidor: $(hostname)</h2>" > /usr/share/nginx/html/index.html' ]           
          name: cloudinitdisk
