apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: base-vm 
  name: base-vm
  namespace: beehive-virtual-machines
spec:    
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/domain: base-vm    
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 2
            threads: 1
          memory:
            guest: 2048M
          devices:
            disks:
            - disk:
                bus: virtio
              name: vm-rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        volumes:
        - persistentVolumeClaim:
              claimName: base-vm-disk
          name: vm-rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: 'redhat1234' 
              chpasswd: { expire: False }
              write_files:
                - path: /etc/yum.repos.d/centos-stream.repo
                  content: |
                    [baseos]
                    name=CentOS Stream $releasever - BaseOS
                    mirrorlist=http://mirrorlist.centos.org/?release=9-stream&arch=$basearch&repo=baseos
                    enabled=1
                    gpgcheck=1
                    gpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official

                    [appstream]
                    name=CentOS Stream $releasever - AppStream
                    mirrorlist=http://mirrorlist.centos.org/?release=9-stream&arch=$basearch&repo=appstream
                    enabled=1
                    gpgcheck=1
                    gpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official

              packages:
                - nginx
                - firewalld
                - openssh-server
              runcmd:
                - echo "CLOUD-INIT TEST OK" > /root/cloud-init-test.txt
                - systemctl enable sshd
                - systemctl start sshd
                - systemctl enable firewalld
                - systemctl start firewalld
                - firewall-cmd --permanent --add-service=ssh
                - firewall-cmd --permanent --add-service=http
                - firewall-cmd --permanent --add-service=https
                - firewall-cmd --reload
                - echo "<h1>GitOps com ArgoCD + Cloud-Init!</h1><h2>Servidor: $(hostname)</h2>" > /usr/share/nginx/html/index.html

              
          name: cloudinitdisk
