apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: base-vm 
  name: base-vm
  namespace: beehive-virtual-machines
spec:    
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/domain: base-vm    
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 2
            threads: 1
          memory:
            guest: 2048M
          devices:
            disks:
            - disk:
                bus: virtio
              name: vm-rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        volumes:
        - persistentVolumeClaim:
              claimName: base-vm-disk
          name: vm-rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: 'redhat1234' 
              chpasswd: { expire: False }
              write_files:
                - path: /etc/yum.repos.d/almalinux.repo
                  content: |
                    [baseos]
                    name=AlmaLinux BaseOS
                    baseurl=http://mirror.centos.org/centos/9-stream/BaseOS/x86_64/os/
                    enabled=1
                    gpgcheck=0

                    [appstream]
                    name=AlmaLinux AppStream
                    baseurl=http://mirror.centos.org/centos/9-stream/AppStream/x86_64/os/
                    enabled=1
                    gpgcheck=0
              runcmd:
                - echo "CLOUD-INIT TEST OK" > /root/cloud-init-test.txt
                - dnf -y install nginx firewalld openssh-server
                - systemctl enable sshd
                - systemctl start sshd
                - systemctl enable firewalld
                - systemctl start firewalld
                - firewall-cmd --permanent --add-service=ssh
                - firewall-cmd --permanent --add-service=http
                - firewall-cmd --permanent --add-service=https
                - firewall-cmd --reload
                - echo "<h1>Olá do GitOps com ArgoCD + Cloud-Init!</h1>" > /usr/share/nginx/html/index.html
              
          name: cloudinitdisk
